export { default as ButtonMain } from './ButtonMain/ButtonMain.vue'
export { default as ButtonAdd } from './ButtonAdd/ButtonAdd.vue'
export { default as ButtonLogout } from './ButtonLogout/ButtonLogout.vue'
export { default as ButtonEdit } from './ButtonEdit/ButtonEdit.vue'
export { default as ButtonEducation } from './ButtonEducation/ButtonEducation.vue'
export { default as ButtonDelete } from './ButtonDelete/ButtonDelete.vue'
export { default as ButtonSearch } from './ButtonSearch/ButtonSearch.vue'
