export { default as PageTitle } from './PageTitle/PageTitle.vue'
export { default as UserAvatar } from './UserAvatar/UserAvatar.vue'
export { default as AlertNotification } from './AlertNotification/AlertNotification.vue'
export { default as PreloaderBlock } from './PreloaderBlock/PreloaderBlock.vue'
export { default as CategoryCard } from './CategoryCard/CategoryCard.vue'
export { default as BadgeTag } from './BadgeTag/BadgeTag.vue'
export { default as ImageCard } from './ImageCard/ImageCard.vue'
export { default as Image } from './Image/Image.vue'
