export { default as LoginForm } from './LoginForm/LoginForm.vue'
export { default as RegisterForm } from './RegisterForm/RegisterForm.vue'
export { default as StudentForm } from './StudentForm/StudentForm.vue'
export { default as CreatureForm } from './CreatureForm/CreatureForm.vue'
export { default as CreatureCategoryForm } from './CreatureCategoryForm/CreatureCategoryForm.vue'
